kind: Service
apiVersion: v1
metadata:
  name:  flask-docker
spec:
  type: NodePort
  selector:
    app:  flask-docker
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion:  extensions/v1beta1
kind: Deployment
metadata:
  name: flask-docker-deployment
  labels:
    app:  flask-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  flask-docker
    template:
      metadata:
        lables:
          app:  flask-docker
      spec:
        containers:
        - name: flask-docker
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
